### ISSUE TITLE
Dataref byte[] not possibel

### ISSUE THREAD

**Issue by urbanswelt** [wadedos/ExtPlaneJs#4]
I can not read any datarefs with byte definition.
Example :

sim/aircraft/view/acf_tailnum	byte[40]	y	string	Tail number
sim/aircraft/view/acf_author	byte[500]	y	string	Author's Name
sim/aircraft/view/acf_descrip	byte[260]	y	string	Brief description of the plane.  Was 500 chars in older planes.
sim/aircraft/view/acf_notes	byte[240]	y	string	Notes on the plane

**Comment by urbanswelt** [comment]
Quick and dirty Solution for this for Node.js:
edit ExtplaneJs.js section B for Base64 -->>


            // data
            case 'b':
			var b = new Buffer(value, 'base64');
			var s = b.toString();
				return s;
            break;


was from this place --> https://stackoverflow.com/questions/2820249/base64-encoding-and-decoding-in-client-side-javascript

**Comment by urbanswelt** [comment]
OK i see it was already fixed , but not pushed as new Version for 

npm install extplanejs

**Comment by wadedos** [comment]
New NPM tag pushed. Closing.
